name: Build GNU Make

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build unpatched gnumake.exe
        working-directory: make
        run: |
          .\bootstrap.bat
          .\build_w32.bat gcc
          strip --strip-unneeded -o ..\gnumake.exe GccRel\gnumake.exe

      - uses: ncipollo/release-action@v1
        with:
          draft: true
          makeLatest: true
          artifactErrorsFailBuild: true
          bodyFile: .github\release.md
          artifacts: "gnumake.exe"

      - name: Apply busybox-w32.patch
        working-directory: make
        run: patch -p1 -i ..\busybox-w32.patch

      - name: Build patched make.exe
        working-directory: make
        run: |
          ..\gnumake.exe -f Basic.mk TOOLCHAIN=gcc CC=gcc
          strip --strip-unneeded -o ..\make.exe GccRel\gnumake.exe

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "make.exe"
