name: Build GNU Make

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build unpatched gnumake.exe
        working-directory: make
        run: |
          del maintMakefile
          ./bootstrap.bat
          ./build_w32.bat gcc
          strip --strip-unneeded -o ../gnumake.exe GccRel/gnumake.exe

      - name: Apply disable-shell-debug-test.patch
        working-directory: make
        run: patch -p1 -i ../.github/disable-shell-debug-test.patch

      - name: Test gnumake.exe
        working-directory: make
        run: ../gnumake.exe check TOOLCHAIN=gcc

      - name: Apply busybox-w32.patch
        working-directory: make
        run: patch -p1 -i ../busybox-w32.patch

      - name: Build patched make.exe
        working-directory: make
        run: |
          ./build_w32.bat gcc
          strip --strip-unneeded -o ../make.exe GccRel/gnumake.exe

      - name: Test make.exe
        working-directory: make
        run: ../make.exe check TOOLCHAIN=gcc

      - uses: ncipollo/release-action@v1
        with:
          makeLatest: true
          artifactErrorsFailBuild: true
          bodyFile: .github/release.md
          artifacts: "make.exe,gnumake.exe"
